// eslint-disable-next-line import/no-extraneous-dependencies
const colors = require('tailwindcss/colors');

module.exports = {
  mode: 'jit',
  purge: {
    content: [
      './src/pages/**/*.jsx',
      './src/lib/**/*.jsx',
      './src/lib/**/*.js',
      './src/blog-posts/**/*.mdx',
      './src/components/atoms/*.jsx',
      './src/components/molecules/*.jsx',
      './src/components/organisms/*.jsx',
    ],
  },
  darkMode: false, // 'media' or 'class'
  theme: {
    fontFamily: {
      sans: ['Inter'],
      logo: ['Inter'],
      code: ['Fira Mono'],
    },
    extend: {
      colors: {
        gray: {
          xxLightest: colors.trueGray['50'],
          xLightest: colors.trueGray['100'],
          lightest: colors.trueGray['200'],
          lighter: colors.trueGray['300'],
          light: colors.trueGray['400'],
          DEFAULT: colors.trueGray['500'],
          dark: colors.trueGray['600'],
          darker: colors.trueGray['700'],
          darkest: colors.trueGray['800'],
          xDarkest: colors.trueGray['900'],
        },
        primary: {
          xLightest: colors.indigo['100'],
          lightest: colors.indigo['200'],
          lighter: colors.indigo['300'],
          light: colors.indigo['400'],
          DEFAULT: colors.indigo['500'],
          dark: colors.indigo['600'],
          darker: colors.indigo['700'],
          darkest: colors.indigo['800'],
          xDarkest: colors.indigo['900'],
        },
        secondary: {
          xxLightest: colors.sky['50'],
          xLightest: '#eaeef4',
          lightest: colors.sky['200'],
          lighter: colors.sky['300'],
          light: colors.sky['400'],
          DEFAULT: colors.sky['500'],
          dark: colors.sky['600'],
          darker: colors.sky['700'],
          darkest: colors.sky['800'],
          xDarkest: colors.sky['900'],
        },
        info: {
          xLightest: colors.cyan['100'],
          lightest: colors.cyan['200'],
          lighter: colors.cyan['300'],
          light: colors.cyan['400'],
          DEFAULT: colors.cyan['500'],
          dark: colors.cyan['600'],
          darker: colors.cyan['700'],
          darkest: colors.cyan['800'],
          xDarkest: colors.cyan['900'],
        },
        warning: {
          xLightest: colors.amber['100'],
          lightest: colors.amber['200'],
          lighter: colors.amber['300'],
          light: colors.amber['400'],
          DEFAULT: colors.amber['500'],
          dark: colors.amber['600'],
          darker: colors.amber['700'],
          darkest: colors.amber['800'],
          xDarkest: colors.amber['900'],
        },
        success: {
          xLightest: colors.green['100'],
          lightest: colors.green['200'],
          lighter: colors.green['300'],
          light: colors.green['400'],
          DEFAULT: colors.green['500'],
          dark: colors.green['600'],
          darker: colors.green['700'],
          darkest: colors.green['800'],
          xDarkest: colors.green['900'],
        },
        danger: {
          xLightest: colors.rose['100'],
          lightest: colors.rose['200'],
          lighter: colors.rose['300'],
          light: colors.rose['400'],
          DEFAULT: colors.rose['500'],
          dark: colors.rose['600'],
          darker: colors.rose['700'],
          darkest: colors.rose['800'],
          xDarkest: colors.rose['900'],
        },
        white: colors.white,
        black: colors.black,
      },
    },
  },
};
